name: Container
on:
  [push]

jobs:
  create-docker-centos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitLab
        uses: docker/login-action@v1 
        with:
          registry: registry.git.rwth-aachen.de
          username: ${{ secrets.RWTH_GITLAB_REGISTRY_USER }}
          password: ${{ secrets.RWTH_GITLAB_REGISTRY }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
         file: Packaging/Docker/Dockerfile.dev-centos
         push: true
         tags: registry.git.rwth-aachen.de/acs/public/simulation/dpsim/dpsim:dpsim-centos

  create-docker-fedora-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitLab
        uses: docker/login-action@v1 
        with:
          registry: registry.git.rwth-aachen.de
          username: ${{ secrets.RWTH_GITLAB_REGISTRY_USER }}
          password: ${{ secrets.RWTH_GITLAB_REGISTRY }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
         file: Packaging/Docker/Dockerfile.dev
         push: true
         tags: registry.git.rwth-aachen.de/acs/public/simulation/dpsim/dpsim:dpsim-dev

